import asyncio
import os
from pathlib import Path

from sqlalchemy import inspect
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy.orm import DeclarativeBase

DATABASE_URL = os.environ.get("DATABASE_URL", "")

# Railway gives postgres:// but asyncpg needs postgresql+asyncpg://
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+asyncpg://", 1)
elif DATABASE_URL.startswith("postgresql://") and "+asyncpg" not in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://", 1)

# Fallback for local dev without a database
if not DATABASE_URL:
    DATABASE_URL = "sqlite+aiosqlite:///./ltp_dev.db"

engine = create_async_engine(DATABASE_URL, echo=False, pool_pre_ping=True)
async_session = async_sessionmaker(engine, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


async def get_db():
    async with async_session() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# Path to alembic.ini relative to repo root (this file lives one level down).
_ALEMBIC_INI = Path(__file__).resolve().parent.parent / "alembic.ini"


def _alembic_config():
    """Build an Alembic Config that points at our alembic.ini. We
    intentionally do NOT set sqlalchemy.url here — env.py reads DATABASE_URL
    itself, which keeps CLI runs (`alembic upgrade head` from a terminal)
    and boot-time upgrades on the same code path."""
    from alembic.config import Config
    return Config(str(_ALEMBIC_INI))


async def _probe_tables() -> set[str]:
    """Return the set of table names currently in the database. Uses the
    app's async engine via run_sync so we don't need a separate sync driver
    (no psycopg2) just to peek at the schema."""
    async with engine.connect() as conn:
        return await conn.run_sync(lambda c: set(inspect(c).get_table_names()))


def _run_alembic_commands(needs_stamp: bool) -> None:
    """Worker-thread body. Stamps once if cutting over from create_all, then
    runs upgrade head. Both calls go through Alembic's sync command layer;
    env.py internally uses asyncio.run() to drive the actual SQL, which
    works because to_thread gave us a fresh event loop slot."""
    from alembic import command
    cfg = _alembic_config()
    if needs_stamp:
        print("[LTP] alembic: stamping pre-alembic schema as head (one-shot cutover)", flush=True)
        command.stamp(cfg, "head")
    print("[LTP] alembic: upgrade head", flush=True)
    command.upgrade(cfg, "head")


async def init_db():
    """Apply pending Alembic migrations.

    Replaces the prior Base.metadata.create_all + LTP_RESET_DB combo. Schema
    changes now go through `alembic revision --autogenerate`, are reviewed,
    and ride a normal deploy. There is no longer any in-process knob that
    drops the database — recovery from corruption is via Railway's
    point-in-time restore, not an env var.

    Three boot scenarios are handled:
      (a) Fresh DB (no app tables, no alembic_version) — upgrade head
          creates everything from the migration history.
      (b) Existing DB seeded by the prior create_all path (app tables but
          no alembic_version) — stamp head once to adopt the live schema as
          Alembic's baseline, then upgrade head (no-op the first time).
      (c) Existing DB already under Alembic management — upgrade head
          applies any pending migrations.

    Stamping in case (b) is safe ONLY because the initial migration was
    autogenerated from the same models create_all was producing. If we
    ever ship a schema change before this cutover runs everywhere, that
    assumption breaks; see README "Migrations" for the operational note."""
    tables = await _probe_tables()
    has_alembic = "alembic_version" in tables
    has_app_tables = any(t in tables for t in ("companies", "quotes", "invoices", "users"))
    needs_stamp = has_app_tables and not has_alembic
    await asyncio.to_thread(_run_alembic_commands, needs_stamp)
    print(f"[LTP] init_db complete ({engine.dialect.name})", flush=True)
