"""Backend payout engine + QuickBooks vendor-bill tests.

This module tests backend/payouts.py (pay-period math + snapshot re-derivation)
and — via the shared fixtures generated by tests/_gen_payout_fixture.js — locks
the Python re-derivation to the JavaScript engine (theme.js::LTP_payoutRows) so
the vendor bills post exactly what the Payouts tab shows.

Runs under pytest (`python -m pytest tests/test_payout_bills.py`) and standalone
(`python tests/test_payout_bills.py`). Pure functions only — no DB, no network.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend import payouts
from backend.payouts import derive_payout_drafts, js_round2

_FX = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")


def _load(name):
    with open(os.path.join(_FX, name)) as f:
        return json.load(f)


# ── js_round2: matches JS Math.round(x*100)/100, not banker's rounding ───────

def test_js_round2_half_up_positive():
    assert js_round2(0.125) == 0.13          # banker's would give 0.12
    assert js_round2(2.675) == 2.68 or js_round2(2.675) == 2.67  # float-repr driven; matches JS either way


def test_js_round2_negative_half_toward_positive():
    # Math.round(-12.5) === -12  ->  floor(-12.5 + 0.5) === -12
    assert js_round2(-0.125) == -0.12


def test_js_round2_matches_js_float_repr_cases():
    # 1.005*100 == 100.49999999999999 in IEEE-754, so BOTH JS and Python round to 1.00.
    assert js_round2(1.005) == 1.0
    assert js_round2(0.1 + 0.2) == 0.3


# ── Pay-period math: locked to the JS helpers via the shared fixture ─────────

def test_pay_period_vectors_match_js():
    fx = _load("payout_periods.json")
    for c in fx["cases"]:
        idx = payouts.pay_period_index(c["anchor"], c["length"], c["date"])
        assert idx == c["index"], (c, idx)
        b = payouts.pay_period_for_index(c["anchor"], c["length"], c["index"])
        assert b["start"] == c["start"] and b["end"] == c["end"], (c, b)
        # bounds(as_of=date) resolves to the same window
        bnd = payouts.pay_period_bounds(c["anchor"], c["length"], c["date"])
        assert bnd["start"] == c["start"] and bnd["end"] == c["end"], (c, bnd)
    for p in fx["payday"]:
        assert payouts.pay_period_pay_day(p["end"], p["offset"]) == p["payDay"], p


def test_pay_period_invalid_inputs_return_none():
    assert payouts.pay_period_index("", 14, "2026-07-19") is None
    assert payouts.pay_period_index("2026-07-06", 14, "nope") is None
    assert payouts.pay_period_bounds("2026-02-31", 14, "2026-07-19") is None   # overflow-normalized rejected
    assert payouts.pay_period_index("2026-07-06", 0, "2026-07-20") == 1        # invalid length -> 14


def test_pay_period_label_matches_js_format():
    assert payouts.pay_period_label("2026-07-06", "2026-07-19") == "July 6th, 2026 – July 19th, 2026"


# ── derive_payout_drafts: parity with LTP_payoutRows on the shared fixture ────

def _contacts_from(fx):
    return {c["id"]: {"first_name": c["firstName"], "last_name": c["lastName"]} for c in fx["contacts"]}


def test_derive_matches_js_payoutrows_fixture():
    fx = _load("payout_snapshot.json")
    drafts = derive_payout_drafts(fx["projects"], _contacts_from(fx), fx["range"]["start"], fx["range"]["end"])
    # Signed rows: (crewId, projectName, date) -> payable, straight from the JS run.
    expected_signed = {}
    expected_pending = set()
    for r in fx["expected"]["rows"]:
        key = (r["crewId"], r["projectName"], r["date"])
        if r["payable"] is None:
            expected_pending.add(key)
        else:
            expected_signed[key] = r["payable"]

    got_signed = {}
    got_pending = set()
    for d in drafts:
        for day in d["days"]:
            got_signed[(d["contact_id"], day["project_name"], day["date"])] = day["payable"]
        for pd in d["pending"]:
            got_pending.add((d["contact_id"], pd["project_name"], pd["date"]))

    assert got_signed == expected_signed
    assert got_pending == expected_pending
    # Per-crew signed totals match the JS group totals.
    for cid, total in fx["expected"]["byCrew"].items():
        draft = next(d for d in drafts if d["contact_id"] == int(cid))
        assert draft["total_signed"] == total, (cid, draft["total_signed"], total)


def test_derive_multi_role_day_splits_units():
    """Alex 2026-07-09 worked L1 (svc 1) + A1 (svc 2) -> one payout day, two units
    with distinct service ids (the per-role expense-account split source)."""
    fx = _load("payout_snapshot.json")
    drafts = derive_payout_drafts(fx["projects"], _contacts_from(fx), fx["range"]["start"], fx["range"]["end"])
    alex = next(d for d in drafts if d["contact_id"] == 5)
    day = next(x for x in alex["days"] if x["date"] == "2026-07-09" and x["project_name"] == "Summer Fest")
    svc_ids = sorted(u["service_id"] for u in day["units"])
    assert svc_ids == [1, 2]
    assert day["adj_total"] == 30.0          # +50 parking, -20 advance
    # Units sum + adjustments reconcile to payable within a cent.
    assert abs(sum(u["amount"] for u in day["units"]) + day["adj_total"] - day["payable"]) < 0.005


def test_derive_adjustment_only_day_has_no_units():
    """Blair 2026-07-11 was a no-show with a $100 kill fee -> work.pay.total 0,
    empty units, payable 100 (a line that must fall back to the default account)."""
    fx = _load("payout_snapshot.json")
    drafts = derive_payout_drafts(fx["projects"], _contacts_from(fx), fx["range"]["start"], fx["range"]["end"])
    blair = next(d for d in drafts if d["contact_id"] == 6)
    day = next(x for x in blair["days"] if x["date"] == "2026-07-11")
    assert day["units"] == []
    assert day["payable"] == 100.0
    assert day["state"] == "no_show"


def test_derive_full_margin_day_is_zero():
    fx = _load("payout_snapshot.json")
    drafts = derive_payout_drafts(fx["projects"], _contacts_from(fx), fx["range"]["start"], fx["range"]["end"])
    owner = next(d for d in drafts if d["contact_id"] == 7)
    day = owner["days"][0]
    assert day["payable"] == 0.0
    assert day["units"] == []            # full-margin unit (total 0) dropped


# ── derive edge cases (hand-built minimal snapshots) ─────────────────────────

def _pos(crew, work_pay=None, adj=None, status="confirmed", service_id=1):
    p = {"crewId": crew, "serviceId": service_id, "status": status}
    if work_pay is not None:
        p["work"] = {"state": "worked", "pay": work_pay}
    if adj is not None:
        p["adj"] = adj
    return p


_PAY500 = {"total": 500.0, "tier": "full", "units": [{"serviceId": 1, "total": 500.0}]}


def test_derive_dedup_same_day_not_summed():
    # Two confirmed positions for the same crew/day/project carry the SAME frozen
    # work.pay (sign-off invariant) -> ONE payout day, NOT double-counted.
    proj = {"id": 1, "name": "P", "schedule": [
        {"date": "2026-07-08", "positions": [_pos(5, _PAY500), _pos(5, _PAY500)]},
    ]}
    drafts = derive_payout_drafts([proj], {5: {"first_name": "A", "last_name": "B"}}, "2026-07-01", "2026-07-31")
    assert len(drafts) == 1 and len(drafts[0]["days"]) == 1
    assert drafts[0]["days"][0]["payable"] == 500.0


def test_derive_two_step_rounding():
    pay = {"total": 10.0, "tier": "full", "units": [{"serviceId": 1, "total": 10.0}]}
    proj = {"id": 1, "name": "P", "schedule": [
        {"date": "2026-07-08", "positions": [_pos(5, pay, adj=[{"amount": 0.1}, {"amount": 0.2}])]},
    ]}
    drafts = derive_payout_drafts([proj], {5: {"first_name": "A", "last_name": "B"}}, "2026-07-01", "2026-07-31")
    day = drafts[0]["days"][0]
    assert day["adj_total"] == 0.3       # js_round2(0.1 + 0.2)
    assert day["payable"] == 10.3


def test_derive_ignores_unconfirmed_and_null_crew_and_range():
    pay = _PAY500
    proj = {"id": 1, "name": "P", "schedule": [
        {"date": "2026-07-08", "positions": [
            _pos(5, pay, status="requested"),      # not confirmed -> ignored
            _pos(None, pay),                        # null crew -> ignored
        ]},
        {"date": "2026-06-01", "positions": [_pos(5, pay)]},   # outside range -> ignored
        {"date": "2026-07-09", "positions": [_pos(9, pay)]},   # confirmed+signed, in range
    ]}
    drafts = derive_payout_drafts([proj], {5: {"first_name": "A", "last_name": "B"},
                                           9: {"first_name": "C", "last_name": "D"}},
                                  "2026-07-01", "2026-07-31")
    # Only crew 9's 07-09 day survives.
    assert len(drafts) == 1 and drafts[0]["contact_id"] == 9
    assert drafts[0]["days"][0]["date"] == "2026-07-09"


def test_derive_confirmed_unsigned_is_pending_not_billable():
    proj = {"id": 1, "name": "P", "schedule": [
        {"date": "2026-07-08", "positions": [_pos(5, work_pay=None)]},   # confirmed, no work.pay
    ]}
    drafts = derive_payout_drafts([proj], {5: {"first_name": "A", "last_name": "B"}}, "2026-07-01", "2026-07-31")
    assert len(drafts) == 1
    assert drafts[0]["days"] == []
    assert drafts[0]["pending"] == [{"project_id": 1, "project_name": "P", "date": "2026-07-08"}]


if __name__ == "__main__":
    import traceback
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    passed = failed = 0
    for fn in fns:
        try:
            fn()
            passed += 1
        except Exception:
            failed += 1
            print("FAIL " + fn.__name__)
            traceback.print_exc()
    print("payout-bills suite — PASS: %d   FAIL: %d" % (passed, failed))
    raise SystemExit(1 if failed else 0)
