#!/usr/bin/env python3
"""Build the crew briefing from one template into its two targets.

    python docs/crew-briefing/build.py

Writes:
    assets/crew-email/announcement.html   the public page (served by the app)
    docs/crew-briefing/out/artifact.html  paste-target for the Claude artifact
    docs/crew-briefing/out/email.html     the email body, for pasting into Gmail

The page and the artifact must LOOK identical, so they share template.html and
differ only where the delivery medium forces it:

  fonts   artifact: its host allows stylesheets only from fonts.googleapis.com.
          page:     this app's CSP is font-src 'self' (backend/main.py::_CSP),
                    so DM Sans comes from the self-hosted /assets/fonts.css.
          Same typeface either way. DM Mono is NOT self-hosted, so neither
          target uses it — both fall back to the app's own mono stack, the one
          modules/crew-view.js uses.

  images  artifact: its host blocks external images -> inlined as data: URIs.
          page:     served from /assets/crew-email/ -> ~16 KB, not ~560 KB.

  scripts artifact: inline <script> is allowed, so it carries the sender
                    toolbar (type "ltp") with the copy-for-Gmail buttons.
          page:     this app's CSP is script-src 'self' with no 'unsafe-inline',
                    so an inline script is refused outright — the buttons would
                    render and silently do nothing. The toolbar is stripped
                    instead of widening the CSP for a static page. It is hidden
                    from crew in the artifact anyway, so both still look alike.

Edit template.html (or email-body.html / email.txt) and re-run; never hand-edit
the generated files.
"""
import base64, json, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HERE = os.path.join(REPO, "docs", "crew-briefing")
OUT = os.path.join(HERE, "out")
sys.path.insert(0, REPO)

# Absolute origin for the images the EMAIL references (a mail client has no
# site-relative base). Matches _app_origin()'s canonical host.
ORIGIN = "https://app.luminarytechnology.productions"

IMAGES = {
    "__MASTHEAD__":  "assets/logos/luminary-masthead.png",
    "__EMAIL__":     "assets/crew-email/01-request-email.jpg",
    "__RESPOND__":   "assets/crew-email/02-call-sheet-respond.jpg",
    "__CONFIRMED__": "assets/crew-email/03-confirmed.jpg",
}
MIME = {".png": "image/png", ".jpg": "image/jpeg"}

# The email signature's images. Email and page use the owner's own hosted URLs
# (the app's CSP img-src already allows both hosts, and they stay in step with
# whatever he updates on the website); the artifact inlines local copies,
# because its host blocks external images outright.
SIG_IMAGES = {
    "__SIG_LOGO__":  ("https://www.luminarytechnology.productions/?attachment_id=581",
                      "docs/crew-briefing/sig/logo.png"),
    "__SIG_PHOTO__": ("https://www.luminarytechnology.productions/wp-content/uploads/2024/07/Landry-Profile1.png",
                      "docs/crew-briefing/sig/photo.png"),
    "__SIG_FB__":    ("https://storage.googleapis.com/signaturesatori/icons/cf/16/ff6633/facebook.png",
                      "docs/crew-briefing/sig/facebook.png"),
    "__SIG_IG__":    ("https://storage.googleapis.com/signaturesatori/icons/cf/16/ff6633/instagram.png",
                      "docs/crew-briefing/sig/instagram.png"),
}

# Where the standalone page lives — the target of the email's "view in browser"
# link. Only the email carries that link: the page IS the browser view.
PAGE_URL = ORIGIN + "/assets/crew-email/announcement.html"

# The page's toolbar script, split out of the template (CSP: script-src 'self').
SCRIPT_REL = "assets/crew-email/briefing.js"

GFONTS = ('<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
          'family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;'
          '0,9..40,700;1,9..40,400&display=swap">')
SELF_HOSTED = '<link rel="stylesheet" href="/assets/fonts.css">'

PAGE_HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="How Luminary sends crew requests, and how to accept or pass on a shift.">
<meta name="robots" content="noindex">
<!-- GENERATED by docs/crew-briefing/build.py — do not hand-edit. -->
</head>
<body>
"""


def write(path, text):
    with open(path, "w") as fh:
        fh.write(text)


def signature(target):
    """The email signature, with its images resolved for this target."""
    sig = open(os.path.join(HERE, "signature.html"), encoding="utf-8").read().strip()
    for tok, (url, local) in SIG_IMAGES.items():
        sig = sig.replace(tok, data_uri(local) if target == "artifact" else url)
    return sig


def data_uri(rel):
    with open(os.path.join(REPO, rel), "rb") as fh:
        blob = base64.b64encode(fh.read()).decode()
    return "data:" + MIME[os.path.splitext(rel)[1]] + ";base64," + blob


def render_email():
    """The email body, wrapped in the same shell every crew email uses."""
    import asyncio
    from backend.email_compose import email_shell, _email_brand
    # The masthead URL is derived from the OAuth redirect host; pin it so the
    # build does not depend on the developer's environment.
    os.environ.setdefault("LTP_OAUTH_REDIRECT_URI", ORIGIN + "/auth/callback")
    os.environ.setdefault("LTP_TOKEN_ENCRYPTION_KEY", "")
    body = open(os.path.join(HERE, "email-body.html"), encoding="utf-8").read()
    body = body.replace("__SIGNATURE__", signature("email")).replace("__PAGEURL__", PAGE_URL)
    # A mail client has no site-relative base, so the screenshots need absolute
    # URLs — unlike the page, which links them site-relative.
    for tok, rel in IMAGES.items():
        body = body.replace(tok, ORIGIN + "/" + rel)
    left = re.findall(r"__[A-Z_]+__", body)
    assert not left, "unsubstituted placeholders in email body: %s" % left
    brand = _email_brand({"companyName": "Luminary Technology & Productions",
                          "website": "LuminaryTechnology.Productions",
                          "accentColor": "#EF5822"})
    inner = ('<div style="font-size:16px;line-height:1.62;color:#3A4A54">'
             + body + '</div>')
    return email_shell(inner, brand)


def build(target, email_html, plain):
    """Render the template for one target. Returns the HTML; for the page it
    also writes the toolbar script out as a separate file."""
    s = open(os.path.join(HERE, "template.html")).read()
    if target == "artifact":
        s = s.replace("__FONTLINK__", GFONTS)
        for tok, rel in IMAGES.items():
            s = s.replace(tok, data_uri(rel))
    else:
        s = s.replace("__FONTLINK__", SELF_HOSTED)
        for tok, rel in IMAGES.items():
            s = s.replace(tok, "/" + rel)

    # Substitute BEFORE splitting the script out, so the emitted .js carries the
    # real payload rather than the placeholders.
    s = s.replace("__SIGNATURE__", signature(target)).replace("__PAGEURL__", PAGE_URL)
    s = s.replace("__EMAILHTML__", json.dumps(email_html)).replace("__PLAINTEXT__", json.dumps(plain))
    left = re.findall(r"__[A-Z]+__", s)
    assert not left, "unsubstituted placeholders: %s" % left

    if target != "artifact":
        # The toolbar stays — but its script has to become a real file. This
        # app's CSP is script-src 'self' with no 'unsafe-inline', so an inline
        # <script> is refused outright and the buttons would render dead. A
        # same-origin file satisfies 'self' without loosening the policy.
        head, sep, rest = s.partition("<script>")
        assert sep, "script block not found in template"
        body, sep2, tail = rest.partition("</script>")
        assert sep2, "unterminated script block in template"
        write(os.path.join(REPO, SCRIPT_REL), body.strip() + "\n")
        s = head.rstrip() + '\n<script src="/' + SCRIPT_REL + '"></script>\n' + tail.strip()
    return s


def main():
    os.makedirs(OUT, exist_ok=True)
    email_html = render_email()
    plain = open(os.path.join(HERE, "email.txt")).read()

    open(os.path.join(OUT, "email.html"), "w").write(email_html)
    open(os.path.join(OUT, "artifact.html"), "w").write(build("artifact", email_html, plain))
    page = PAGE_HEAD + build("page", email_html, plain) + "\n</body>\n</html>\n"
    open(os.path.join(REPO, "assets", "crew-email", "announcement.html"), "w").write(page)

    for label, path in (("page", "assets/crew-email/announcement.html"),
                        ("script", SCRIPT_REL),
                        ("artifact", "docs/crew-briefing/out/artifact.html"),
                        ("email", "docs/crew-briefing/out/email.html")):
        print("%-9s %6.1f KB  %s" % (label, os.path.getsize(os.path.join(REPO, path)) / 1024, path))


if __name__ == "__main__":
    main()
