"""email_recipients table for per-recipient tracking

Revision ID: ffdf5b454468
Revises: 032148b103b7
Create Date: 2026-06-19 20:41:46.655730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdf5b454468'
down_revision: Union[str, None] = '032148b103b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_role', sa.String(length=4), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=64), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('pdf_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_recipients_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_recipients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_recipients_sent_by_user_id'), ['sent_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_recipients_share_token'), ['share_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_recipients_tracking_token'), ['tracking_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_recipients_tracking_token'))
        batch_op.drop_index(batch_op.f('ix_email_recipients_share_token'))
        batch_op.drop_index(batch_op.f('ix_email_recipients_sent_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_recipients_id'))
        batch_op.drop_index(batch_op.f('ix_email_recipients_entity_id'))

    op.drop_table('email_recipients')
    # ### end Alembic commands ###
