"""user gmail tokens + title + phone columns

Revision ID: 032148b103b7
Revises: 80d4b3f34f51
Create Date: 2026-06-18 00:49:27.690999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032148b103b7'
down_revision: Union[str, None] = '80d4b3f34f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gmail_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gmail_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('gmail_granted_scopes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('title')
        batch_op.drop_column('gmail_granted_scopes')
        batch_op.drop_column('gmail_token_expires_at')
        batch_op.drop_column('gmail_access_token')
        batch_op.drop_column('gmail_refresh_token')

    # ### end Alembic commands ###
